name: Deploying new version of portkey to prod

on:
  push:
    branches:
      - lamatic-main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'
      
      - name: Install dependencies
        run: |
          npm i

      - name: Build wrangler config
        env:
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}
        run: |
          node build.mjs

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./
      
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        id: run-tests
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVICE_URL: ${{ secrets.BASE_URL }}
        run: |
          # Wait for service to be fully available
          sleep 10
          pytest ./tests/model.py -v
          
